### ISSUE TITLE
"varimax" and "quartimax" seem to produce the same outcomes. 

### ISSUE THREAD

**Issue by tomasfernandez1212** [bmcmenamin/fa_kit#2]

**Comment by bmcmenamin** [comment]
Hey Tomas,

I've noticed that happening a lot as well. I've noticed that it happens regardless of whether you use a pure-python or tensorflow rotation method. Those two each use different approaches to optimizing the varimax/quartiamx criteria, so I doubt that this is due to algorithm bug.

I *think* that the issue is that for many datasets the two criteria will result in components that are really similar. I don't have a strong intuition for when that would happen, but it definitely seems that way for small toy datasets.

If you have an example where this is happening and you know that it's wrong, I'd love to see it so I can find where the code is going awry
